### DISCUSSION TITLE
How to use Tor with Searx when using Docker?

### DISCUSSION THREAD

**Discussion by ghost** [searx/searx#1723] [Installation issue: Docker]

**Comment by MarcAbonce** [comment]
What do you mean? Do you want to create a searx onion service using Docker or do you mean something else?

**Comment by ghost** [comment]
I want to run Searx using Docker (in host network mode) and I am running Tor in local system. What I want is for Searx to channel all requests (DNS and POST search requests) through Tor. Is that possible? I want to exclusively run Searx in local network and would use local IP like https://192.168.0.20

**Comment by MarcAbonce** [comment]
It can be done, but I don't think there's a Dockerfile that does that out of the box.

If your container has Tor installed and running already, then you just have to modify your settings.yml to uncomment the proxies section and add:
```
proxies  :  
    http  : socks5h://127.0.0.1:9050  
    https : socks5h://127.0.0.1:9050
```
Assuming that Tor is listening to the 9050 port.

You will probably want to increase the `request_timeout` setting as well because requests take longer with Tor and probably also change the default engines because at least Google requires Captcha with almost every exit node.

**Comment by ghost** [comment]
Thanks for the prompt response. After reading your comment, I mounted the settings.yml  manually through docker volume and modified the settings. However, I noticed that it is still using my local DNS provider for name resolution. Is there a way to fix this? I want it to tunnel all data, both DNS and search, through tor, so that it is oblivious to the outside world.

**Comment by MarcAbonce** [comment]
I haven't been able to reproduce your issue locally. Once I start searx with the socks5h proxies setting, I don't see any DNS lookups coming out.

You're using [the socks5h scheme (with the h at the end) instead of socks5](https://github.com/psf/requests/blob/master/docs/user/advanced.rst#socks), right?
Do the local DNS lookups happen on every query or do they only happen with some engines?

**Comment by ghost** [comment]
Yeah, I am using the exact proxy setting as you mentioned above. In my server, Tor is running with default settings and some other applications are using Tor without any issues.

This is my docker-compose for searx:

  
```
 searx:
        container_name: searx
        image: {custom repo}
        restart: unless-stopped
        network_mode: "host"
        environment:
            IMAGE_PROXY: "True"
            BASE_URL: "https://192.168.1.20:42069"
        volumes:
            - "$HOME/Docker/Searx/:/usr/local/searx/searx/"
```


I have disabled bin/yahoo/google and using primarily DDG & Startpage and for every search through https://192.168.1.20:42069, my pihole (which is my default DNS server) is picking up all the queries. I am using nginx for the SSL.

**Comment by ki9us** [comment]
When you use `localhost` or `127.0.0.1` in your proxy settings when running searx in a container, it refers to the container.  I assume you have tor running on the host machine at `:9050` and the searx container can't see it.  This is good; the searx container is isolated from the host's services for security.  

I couldn't figure out how to tell the container how to access the host, and didn't really want to.  Instead, I moved tor to a container.  That is, you can stop and disabled systemd's tor service, and change your docker-compose.yml to: 

```yml
  tor:
    image: osminogin/tor-simple
    restart: always
    ports:
      - "9050:9050"
  searx:
    container_name: searx
    image: {custom repo}
    depends_on:
      - tor
    restart: unless-stopped
    environment:
      IMAGE_PROXY: "True"
      BASE_URL: "https://192.168.1.20:42069"
    volumes:
      - "$HOME/Docker/Searx/:/usr/local/searx/searx/"
```

And then change the proxy in `settings.yml` to the name of the container: 

```
proxies  :  
    http  : socks5://tor:9050  
    https : socks5://tor:9050
```

If you leave out the `ports: "9050:9050"` part, searx will still be able to reach the tor proxy through the docker network, but 9050 won't be exposed to the host machine.  So you can leave those lines out if you *only* need tor for searx. 

I did this but tbh I wasn't sure how to tell if it was working or not.
