### DISCUSSION TITLE
RSS feed as search engine

### DISCUSSION THREAD

**Discussion by winux1** [searx/searx#2526] [General]
I would like to add a private search engine. My engine basically is a RSS feed. Can I add my RSS feed to searx and search it.

Thanks for your help in advance!

**Comment by unixfox** [comment]
I don't think it's possible for the moment. RSS or Atom feeds can't be added as a new search engine.

You may open a feature request for that though.

**Reply by dalf** [reply]
It is should be possible using the xpath engine.

Untested:

```yaml
  - name : my rss engine
    engine : xpath
    search_url : https://example.com/feed.rss?search={query}
    results_xpath : './channel/item'
    url_xpath : './link/text()'
    title_xpath : './title/text()'
    content_xpath : './description/text()'
    categories : general
```

(see https://github.com/searx/searx/blob/master/searx/engines/bing_news.py for reference)
