### DISCUSSION TITLE
Cannot parse selector Header in rules.json => All engines timing out

### DISCUSSION THREAD

**Discussion by rwjack** [searx/searx#3013] [Installation issue: Docker] [answered]
**Version of Searx, commit number if you are using on master branch and stipulate if you forked Searx**

**How did you install Searx?**
`Searx-docker -> exact git instructions`

**What happened?**
Searx worked now it doesn't. Have no idea how to debug. Upon container restart I got this error with filtron:
`
2021/10/11 17:06:43 Cannot parse rules: Cannot parse selector 'Header:X-Forwarded-For=nslookup(check.searx.space
)': invalid expression
`
After removing the first rule in `rules.json` filtron goes up, but all the engines get http error. Timeout is set to 15s.

**How To Reproduce**
systemctl start searx-docker.service

**Expected behavior**
Searx to be working as it did since I did no changes to the configuration files. Maybe the docker filtron image changed and screwed something up in the background.

**Screenshots & Logs**

**Additional context**
Maybe dns isn't resolving properly in the container? Since searx only has wget preinstalled,
`wget 1.1.1.1` works, but
`wget google.com` doesn't.

Ping gives me `are you root?` errors even when starting `docker exec -it --user root searx sh`, so I can't test with it.

docker-compose.yml
```
version: '3.7'

services:

  filtron:
    container_name: searx_filtron
    hostname: searx_filtron
    image: dalf/filtron
    restart: unless-stopped
    ports:
      - "172.17.0.1:4040:4040"
      - "172.17.0.1:4041:4041"
    networks:
      external:
        ipv4_address: 10.20.0.10
    command: -listen 0.0.0.0:4040 -api 0.0.0.0:4041 -target searx:8080
    volumes:
      - ./rules.json:/etc/filtron/rules.json:rw
    read_only: true
    cap_drop:
      - ALL

  searx:
    container_name: searx
    hostname: searx
    image: searx/searx:latest
    restart: unless-stopped
    networks:
      external:
        ipv4_address: 10.20.0.11
    command: ${SEARX_COMMAND:-}
    volumes:
      - ./searx:/etc/searx:rw
    environment:
      - BIND_ADDRESS=0.0.0.0:8080
      - BASE_URL=https://${SEARX_HOSTNAME:-localhost}
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE

networks:
  external:
    ipam:
      config:
        - subnet: 10.20.0.8/29
```
