### DISCUSSION TITLE
[Question] where to get good proxies

### DISCUSSION THREAD

**Discussion by condense-fidelity-elope** [searx/searx#3019] [General]
I run the searx instance https://search.blou.xyz and I see that google does not work on it, and some other engines are also ratelimiting. Is there anywhere I could good proxies to solve that, or prefarably a fix that does not cost any extra money

**Comment by unixfox** [comment]
For google you can enable `use_mobile_ui` (true) and you won't get any rate limiting issue anymore ;)

**Reply by condense-fidelity-elope** [reply]
i enabled it in settings.yml and then started searx-docker.service again and it still does not work

**Reply by unixfox** [reply]
`use_mobile_ui` is set to `true` like this:
```yaml
  - name : google
    engine : google
    shortcut : go
    use_mobile_ui: true
```
?
