### DISCUSSION TITLE
searx to  searx

### DISCUSSION THREAD

**Discussion by rafnizp-zz** [searx/searx#3322] [Ideas]
Hi People,

Let's say I have my own instance of  searx and my fried also has it's own instance.
Question:
Is it possible to point my instance and get search results only from his instance?
If yes does anyone have any instructions on how to set this up?
Also if above is possible how to control search content? (what is available publicly and what could be available only after sign in)

Thanks for help

**Comment by kvch** [comment]
Yes, you can query other searx instances. You can find an example configuration in `settings.yml`:
```yaml
  - name : searx
    engine : searx_engine
    shortcut : se
    instance_urls :
        - http://127.0.0.1:8888/
    disabled : True
```

> Also if above is possible how to control search content? (what is available publicly and what could be available only after sign in)

What kind of control do you mean? Making the engine private? Or the searx you want to query needs a token?
