### ISSUE TITLE
Searx doesn't work with outgoing proxies

### ISSUE THREAD

**Issue by ghost** [searx/searx#1345]
I've spent the last 48 hours trying to find out why searx doesn't use my proxy even though it claims it does. My setup is the latest raspbian on the raspi 3B, searx is the latest version, python version is 2.7.
I've tried the possible combinations in the proxies section in settings.yml (with http and https and with socks5) found in various readme files. I've read through all searx issues even dealing only remotely with proxy problems but I couldn't find an answer to my problem. I can also shutdown privoxy (I also tried with polipo) and tor, no matter, searx is still running fine then...
The problem is that it connects directly to the web at port 443 which I only found out through sniffing of the traffic at eth0 and also by debugging tor.
What am I doing wrong?

**Comment by dalf** [comment]
The comments in settings.yml are misleading, the syntax is : 
```yaml
outgoing: # communication with search engines                                                                                                                                                                     
    request_timeout : 2.0 # seconds                                                                                                                                                                               
    useragent_suffix : ""                                                                   
    pool_connections : 100                                                                                                                                         
    pool_maxsize : 10                                                                                                                                                                                                                                      
    proxies :
      http : http://127.0.0.1:8123
      https: http://127.0.0.1:8123
```

```proxies``` has ```outgoing``` parent.

I have check that : 
* the port 8123 is used, using wireshark.
* If I stop polipo, searx doesn't work anymore.
