### ISSUE TITLE
How to have searx use dark mode in private (incognito) windows too?

### ISSUE THREAD

**Issue by earpiece** [searx/searx#1400]
I have set in preferences for searx to use Logicodev Dark, but it does not remember this in private windows of course. I had Startpage set so that it has the same search settings in regular or private windows, but I don't know how to repeat this with searx. Thank you if anyone can help!

Using Firefox Quantum latest on Windows 10 x64

**Comment by beatstick** [comment]
If you run your own instance you can replace the default skin by hand and show the dark skin everywhere:

Enable the dark skin without going to preferences on the browser every time:

/searx/searx/static/themes/oscar/css/logicodev.min.css << replace with logicodev-dark.min.css (rename it and remove old file)

**Comment by fabrei** [comment]
I also asked me, if it is possible to use custom preferences of one searx instance in private window of firerfox. searx instances saves the individual preferences which  I made in a cookie, but firefox deletes cookies after closing. Is there any workaround or idea to load custom preferences in private windows?

**Comment by unixfox** [comment]
Set the type of oscar_style to logicodev-dark in the settings like this:
```yml
ui:
    static_path : "" # Custom static path - leave it blank if you didn't change
    templates_path : "" # Custom templates path - leave it blank if you didn't change
    default_theme : oscar # ui theme
    default_locale : "" # Default interface locale - leave blank to detect from browser information or use codes from the 'locales' config section
    theme_args :
        oscar_style : logicodev-dark # default style of oscar
```
