### ISSUE TITLE
Add Hacker News

### ISSUE THREAD

**Issue by InnovativeInventor** [searx/searx#1456]
It would be nice to add this search engine: https://news.ycombinator.com.

**Comment by jfowl** [comment]
Documentation: https://hn.algolia.com/api

It states that it offers two API endpoints:
- Sorted by relevance, then points, then number of comments: `GET http://hn.algolia.com/api/v1/search?query=...`
- Sorted by date, more recent first `GET http://hn.algolia.com/api/v1/search_by_date?query=... `

Which endpoint should be used?

**Comment by idnovic** [comment]
both. I think when the user just does a search the first should be used. But If a user specifies a timerange the 2nd.

**Comment by jfowl** [comment]
Here is the settings.yml snipet for the first api.
```yaml
  - name: HackerNews
    engine: json_engine
    paging: True
    search_url: https://hn.algolia.com/api/v1/search?query={query}&page={pageno}
    results_query: hits
    url_query: url
    title_query: title
    content_query: ''
    categories: it
    timeout: 2.0
    first_page_num: 0
    disabled: True
    shortcut: hn
```

To use different api endpoints would require a custom engine instead of the json_engine, does @kvch want this? We could also modify json_engine to support dates, as this API provides them.
