### ISSUE TITLE
[Enhancement] Add rotating outgoing proxies

### ISSUE THREAD

**Issue by jfowl** [searx/searx#1512]
Excerpt from settings.yml:
```yaml
    proxies :
        http : http://127.0.0.1:8080
        https: http://127.0.0.1:8080
    source_ips:
        - 1.1.1.1
        - 1.1.1.2
```

Search engines, especially google, tend to captcha-block your IP after too many requests. Although this is already somehow addressed with allowing multiple source IPs, not every server does have multiple IPs available.
On the other side, there is only support for a single pair of outgoing proxies. Couldn't we apply the source_ip strategy:
```python
if settings['outgoing'].get('source_ips'):
    http_adapters = cycle(HTTPAdapterWithConnParams(pool_connections=connect, pool_maxsize=maxsize,
                                                    source_address=(source_ip, 0))
                          for source_ip in settings['outgoing']['source_ips'])
```
of cycling to outgoing proxies.
I imagine the settings.yaml format to be changed somewhat like this:
```yaml
    proxies :
        - {http : http://127.0.0.1:8080, https: http://127.0.0.1:8080}
        - {http : http://127.0.0.2:8080, https: http://127.0.0.2:8080}
```

This way, even higher load instances could circumvent some blockage and avoid regular problems like #1441.

I personally think this should not be too difficult to implement, but I suck at python, so...

**Comment by SilverBut** [comment]
Maybe we can use `requests[socks]` so we can [use the socks proxy](http://docs.python-requests.org/en/master/user/advanced/#socks), and have a quick implement of this feature using `proxychains`?

But I also think this feature should be added into the roadmap. And maybe the following syntax is possible:

```yaml
proxies:
  mode: rotate
  servers:
    - http://user:pwd@proxy.example.org:8080
    - https://user:pwd@proxy.example.org:8443
    - socks5://user:pwd@proxy.example.org:1080
    - morty://morty:key@proxy.example.org:3000
```
