### ISSUE TITLE
Different content for logicodev.css and logicodev.min.css in oscar theme

### ISSUE THREAD

**Issue by meaz** [searx/searx#1967]
Shouldn't `logicodev.css` and `logicodev.min.css` in oscar theme have the same content? I mean, `logicodev.min.css` is just the minify version of  `logicodev.css` so I guess it should.

I found at least one difference, there might be more...

in `logicodev.css` there are two body:
```
body {
  /* Margin bottom by footer height */
  font-family: 'Roboto', Helvetica, Arial, sans-serif;
  margin-bottom: 80px;
  background-color: white;
}
```
and
```
/*Global*/
body {
  background: #1d1f21 none !important;
  color: #D5D8D7 !important;
}
```

in `logicodev.min.css` there is only one: 
`body{font-family:Roboto,Helvetica,Arial,sans-serif;margin-bottom:80px;background-color:#fff}`

so which one is the good one? the white background or the almost back one?

**Comment by return42** [comment]
Strange .. what distro of searx you are using, in the master tree: [logicodev.min.css](https://github.com/asciimoo/searx/blob/master/searx/static/themes/oscar/css/logicodev.min.css):

````css
    body{font-family:Roboto,Helvetica,Arial,sans-serif;margin-bottom:80px;background-color:#fff}body a{color:#08c}
````

Which is a *uglify* version of: [logicodev.css](https://github.com/asciimoo/searx/blob/master/searx/static/themes/oscar/css/logicodev.css#L9)

````css
body {
  /* Margin bottom by footer height */
  font-family: 'Roboto', Helvetica, Arial, sans-serif;
  margin-bottom: 80px;
  background-color: white;
}
body a {
  color: #0088cc;
}
````
