### ISSUE TITLE
Cannot use a path with docker.

### ISSUE THREAD

**Issue by JamsNJellies** [searx/searx#1999]
When using searx with docker and nginx for a reverse proxy.
I cannot move searx under /searx on my domain otherwise it cannot load its resources (css, js, etc)

docker-compose.yml
```yaml
version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/cache/:/etx/nginx/cache
      - /etc/letsencrypt/:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443

  searx:
    image: searx/searx:latest
    container_name: searx
    environment:
      BASE_URL: "http://jamespalmer.xyz/searx/"
    expose:
      - 8080
```

nginx.conf
```
events {

}

http {
     server {
            server_name jamespalmer.xyz;

            location /searx {
                     proxy_pass http://searx:8080;
            }
     }
}
```

**Comment by JamsNJellies** [comment]
Putting searx at / instead of /searx works correctly. Searx seems to be ignoring the BASE_URL environment variable and still looking for its resources under /static instead of /searx/static

**Comment by virtadpt** [comment]
Here's how I did it:

```
        location /searx/static {
            alias /opt/searx/searx/searx/static;
        }
        location /searx {
            uwsgi_param SCRIPT_NAME /searx;
            include uwsgi_params;
            uwsgi_pass 127.0.0.1:8888;
        }
```

Note: I installed uwsgi alongside Searx (`pip install uwsgi`).

**Comment by return42** [comment]
See searx-next docs: https://return42.github.io/searx/admin/installation-nginx.html#a-nginx-searx-site

**Comment by JamsNJellies** [comment]
I'm running this inside a docker container, those methods will not work.

**Comment by JamsNJellies** [comment]
The problem is that the searx docker container is ignoring the BASE_URL environment variable.

**Comment by JamsNJellies** [comment]
What I want to do here is make the searx instance in the docker container look for its resources under /searx/static not /static

**Comment by return42** [comment]
@dalf can you help?

**Comment by dalf** [comment]
I use https://return42.github.io/searx/admin/installation-nginx.html#a-nginx-searx-site  section "..at subdrir URL" but without the ```/static``` section.

docker-compose.yml
```yaml
version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/cache/:/etx/nginx/cache
      - /etc/letsencrypt/:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443

  searx:
    image: searx/searx:latest
    container_name: searx
    environment:
      BASE_URL: "http://localhost/searx/"
    expose:
      - 8080
    volumes:
      - ./searx:/etc/searx
```


nginx.conf
```nginx
events {

}

http {
     server {
            server_name jamespalmer.xyz;

            location /searx {
                     proxy_pass http://searx:8080;
    		     proxy_set_header Host $host;
    		     proxy_set_header Connection       $http_connection;
    		     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    		     proxy_set_header X-Scheme $scheme;
    		     proxy_set_header X-Script-Name /searx;
    		     proxy_buffering off;
            }
     }
}
```

About docker-compose.yml:
* I have changed BASE_URL to localhost (because I used http://localhost/searx to access to the server) 
* ```./searx``` is mounted to ```/etc/searx```, so it is possible to modify ```uwsgi.ini```. There is no need here, but if you need to change it later for any reason, this is the way.
