### ISSUE TITLE
line of config reverts after upgrade

### ISSUE THREAD

**Issue by jt196** [searx/searx#2310]
Folks I'm running this on a Docker instance. Upgrade via Watchtower sometimes reverts 

`base_url : https://<my domain>/`

to 

`base_url : https://192.168.x.x/`

Where the IP address is the address of the local machine. I change it back and it works fine. 

Any ideas why this is happening? Could it be related to Docker-compose settings? Here's my docker-compose file:

```
searx:
    container_name: searx
    # image: searx/searx:0.17.0-80-a2430154
    image: searx/searx:latest
    restart: always
    command: -f
    volumes:
      - ./searxconf:/etc/searx:rw
    environment:
      - BIND_ADDRESS=0.0.0.0:8080
      - BASE_URL=https://${SEARX_HOSTNAME}/
      - MORTY_URL=https://${SEARX_HOSTNAME}/
      - MORTY_KEY=${MORTY_KEY}
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    network_mode: host
    labels:
      - com.centurylinklabs.watchtower.enable=true
    logging:
        driver: loki
        options:
            loki-url: http://192.168.x.x:3100/loki/api/v1/push
```
If you need any log info, please let me know what you're looking for! 

Thanks in advance.
