### ISSUE TITLE
command engine takes the whole user input query

### ISSUE THREAD

**Issue by dalf** [searx/searx#2378]
it takes the whole user input query if i'm not mistaken. so when i query eg. `!mylocalcmd xyz` (mylocalcmd being a custom command engine) then the given command gets the whole "`!mylocalcmd xyz`" as `{{QUERY}}` parameter, eventhough it should interested only in the user part of the query, ie. "xyz".
i found that it extracts the user part into the `user_query_parts` variable in `query.py` (current master commit 2fc3b17), but i can not see how to pass it to the engine.

_Originally posted by @bAndie91 in https://github.com/searx/searx/pull/2128#discussion_r540979339_

**Comment by dalf** [comment]
Can you try with the last commit on the master branch 3c4a9c118844b8d436b1bdb2ece3cd6671371838 ?

I can't reproduce the same issue.

with the engine configuration in settings.yml: 
```yaml
  - name: locate
    engine: command
    command: ['locate', '--existing', '--ignore-case', '{{QUERY}}']
    shortcut: locate
    tokens: []
    disabled: False
    delimiter:
        chars: ' '
        keys: ['line']
```

If I search for `!locate !google searx`, then https://github.com/searx/searx/blob/3c4a9c118844b8d436b1bdb2ece3cd6671371838/searx/engines/command.py#L70 
`query` is `searx` not `!locate !google searx`.
