### ISSUE TITLE
Retry mechanism when a captcha is served but multiple proxies are available

### ISSUE THREAD

**Issue by unixfox** [searx/searx#2439]
**Is your feature request related to a problem? Please describe.**
It is known that Google, Bing and more serve a CAPTCHA when Searx does too many requests.
Currently, we got https://github.com/searx/searx/pull/2319 merged, but it is not response aware which means a proxy could be chosen randomly but still be blocked by the website (Google, Bing and more) and thus render the ability of having multiple proxies less useful.

**Describe the solution you'd like**
A mechanism that will retry with another proxy if the response is a CAPTCHA and multiple proxies are provided inside the settings.yml.
Here is an example of a setting that could be included for both general setting and per engine setting:
```yml
outgoing: # communication with search engines
  proxies:
    retry_on:
      - 429
      - 403
    http:
      - http://proxy1:8080
      - http://proxy2:8080
    https:
      - http://proxy1:8080
      - http://proxy2:8080
```
And for the engine setting:
```yml
- name : google
  engine : google
  shortcut : go
  proxies:
    retry_on:
      - 429
      - 403
    http:
      - http://localhost:9000
      - http://localhost:9001
    https:
      - http://localhost:9000
      - http://localhost:9001
```

I don't know if it's better to use HTTP status code or the CAPTCHA detection added in https://github.com/searx/searx/pull/2375 and https://github.com/searx/searx/pull/2350.
Or instead the retry mechanism could just retry if the engine fails with whatever error (proxy that timeout, CAPTCHA, failed to parse the HTML response and so on). So we would have settings like this instead:
```yml
outgoing: # communication with search engines
  proxies:
    retry_on_error: true
    http:
      - http://proxy1:8080
      - http://proxy2:8080
    https:
      - http://proxy1:8080
      - http://proxy2:8080
```

And for the engine setting:
```yml
- name : google
  engine : google
  shortcut : go
  proxies:
    retry_on_error: true
    http:
      - http://localhost:9000
      - http://localhost:9001
    https:
      - http://localhost:9000
      - http://localhost:9001
```

**Describe alternatives you've considered**
I've a Golang proxy that I wrote for that, but it would be better to have this ability inside Searx itself: https://bitbucket.org/unixfox/rotating-proxy-server

**Additional context**
N/A
