### ISSUE TITLE
Yet another "Rate limit exceeded" issue

### ISSUE THREAD

**Issue by rwjack** [searx/searx#2945]
Hi, I've just brought up a docker instance of searx with the following `docker-compose.yaml`

```
version: '3.7'

services:

  filtron:
    container_name: filtron
    image: dalf/filtron
    restart: always
    ports:
      - "0.0.0.0:4040:4040"
      - "0.0.0.0:4041:4041"
    networks:
      - searx
    command: -listen 0.0.0.0:4040 -api 0.0.0.0:4041 -target searx:8080
    volumes:
      - ./rules.json:/etc/filtron/rules.json:rw
    read_only: true
    cap_drop:
      - ALL

  searx:
    container_name: searx
    image: searx/searx:latest
    restart: always
    networks:
      - searx
    command: ${SEARX_COMMAND:-}
    volumes:
      - ./searx:/etc/searx:rw
    environment:
      - BIND_ADDRESS=0.0.0.0:8080
      - BASE_URL=https://${SEARX_HOSTNAME:-localhost}
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE

networks:
  searx:
```

Searching through `server_IP:4040` works, but searching through `searx.domain.tld` using the nginx-proxy-manager reverse proxy gives the `Rate limit exceeded` error.
I'm having a hard time troubleshooting the issue here.

Neither searx/searx-docker#77 nor searx/searx-docker#85 helped fix the issue.

Any ideas on how to proceed?
