### ISSUE TITLE
Question, feature request: Creation of instance specific categories for local search engines?

### ISSUE THREAD

**Issue by virtadpt** [searx/searx#3057]
**Is your feature request related to a problem? Please describe.**
I have several [Recoll](https://www.lesbonscomptes.com/recoll/) indices on my server for several different archives.  I do not want to put Recoll under the Files category in my Searx instance because that would mix things in with Bittorrent trackers and engines and so forth, which would make finding things in my archives difficult.  My problem is that there is no straightforward way that I can find to create a custom search category in Searx that I can drop arbitrary search engines (like my Recoll indices) into.

**Describe the solution you'd like**
I would like to be able to define a brand-new category in searx/settings.yml (in my case, called "Recoll", though other Searx admins could name theirs whatever they want) that I could add arbitrary search engine definitions to (in my case, my various Recoll indices, though other admins could add whatever they wanted).

**Describe alternatives you've considered**
I've considered setting up a separate Searx server that is only for my Recoll indices.  It seems a bit messy to do it this way, plus I already admin two instances, and three might be overkill.  I've considered reworking all of my API- and RSS- based searches to be bang-specific (i.e., all relevant search engines except for my Recoll indices), but the maintenance overhead (adding bangs for new engines, removing bangs for removed engines) for a couple of hundred agents would be prohibitive.  I've also considered not using Searx for this purpose at all and just using a bunch of copies of [recoll-webui](https://framagit.org/medoc92/recollwebui/) for this; it's an option but I recally like Searx :), and aside from that this seems like a feature that a lot of Searx admins out there could make good use of.

**Additional context**
This is sort of the configuration I'm thinking:

```
search:
    custom_categories:
      - this-is-my-custom-defined-category-here
      - bookmarks
...
  - name: archive@leandra
    engine: recoll
    shortcut: arc
    base_url: 'http://leandra:8000/'
    search_dir: ''
    mount_prefix: /export
    dl_prefix: 'http://leandra/lib/archive/'
    timeout: 30.0
    categories: this-is-my-custom-defined-category-here
    disabled: False
```
So that a search query could look like this:

```
http://localhost:8888/?q={{ message | strip | replace: ' ', '%20' }}&categories=this-is-my-custom-defined-category-here&format=json&language=en-US
```

I'll admit, I might be misunderstanding how Recoll access works.  That's fine.  It's being able to define a new category in Searx that is of interest to me (and hopefully, use to others).

**Comment by 0xhtml** [comment]
As far as I know I think you can already define custom categories by simply assigning engines to a new category.
Example configuration:
```yaml
- name: google
  engine: google
  categories: custom
```
This should appear as a new category called `Custom`.
