### ISSUE TITLE
new settings.yml format ?

### ISSUE THREAD

**Issue by dalf** [searx/searx#314]
New format proposal, to discuss :

``` yaml
general:
    debug: true
server:
    port: 8888
    base_url: False # Set custom base_url. Possible values: False or "https://your.custom.host/location/"
    secret_key: "ultrasecret"  # change this!
    image_proxy : False # Proxying image results through searx
    default_method : "GET" # GET or POST
ui:
    themes_path : "" # Custom ui themes path - leave it blank if you didn't change
    default_theme : oscar # ui theme
    default_locale : "" # Default interface locale - leave blank to detect from browser information or use codes from the 'locales' config
    max_length_description: 1000
    spell_suggestion : True # using suggestions to check spell of search-query
    suggestion_distance : 2 # maximum levenshtein distance for spell-checking
    suggestion_wordlist : False # IN DEVELOPMENT: using wordlist for spelling correction, ATTENTION: For example: '/usr/share/dict/words' require more than 1GB RAM on every thread if used!
outgoing:
    useragent_suffix : "" # suffix of searx_useragent, could contain informations like an email address to the administrator
    proxies:
        http : http://localhost:3128
        https: http://localhost:3128
    dns:
        - 8.8.8.8
        - 8.8.4.4
    source_ips:
        - 1.1.1.1
        - 1.1.1.2
```

bellow `useragent_suffix`, we could add `useragents` : a list to replace the [`gen_useragent` function](https://github.com/asciimoo/searx/blob/master/searx/utils.py#L35) and / or the variables `ua_versions` , `ua_os` and `ua`
