### ISSUE TITLE
The command engine doesn't use the working_dir configuration variable.

### ISSUE THREAD

**Issue by virtadpt** [searx/searx#3189]
Version of Searx: commit 0248777f959ba9ee26fc8f1c367ea4ef2cb5d7cc

Installed by cloning the repo and manually executing searx/webapp.py.

**What happened?**
I am setting up a couple of custom commands using the command.py engine.  Reading the source code for this engine shows that it has a configuration option called [working_dir](https://github.com/searx/searx/blob/master/searx/engines/command.py#L23).  However, as it is currently implemented it can't be changed in settings.yml.  It will always default to `realpath('.')`

**How To Reproduce**
Configure a simple command search:

```
  - name: print working directory
    engine: command
    command: [ 'pwd' ]
    working_dir: "/home/your_home_directory"
    shortcut: pwd
    tokens: []
    disabled: False
    timeout: 120.0
    delimiter:
        chars: ' '
        keys: ['line']
```

Optionally, comment out the other search engines.

Start Searx.

Enter the following search: `!pwd` or `!pwd fooble`

**Expected behavior**
You should see a search result that looks something like this:

`LINE: /home/your_home_directory`

What you get is a search result like this:

`LINE: /path/to/where/you/have/searx`

**Screenshots & Logs**
![Screenshot at 2022-03-17 17-42-03](https://user-images.githubusercontent.com/639730/158915873-73eecd07-ea2d-4028-95fc-edfac1311731.png)

![Screenshot at 2022-03-17 17-42-58](https://user-images.githubusercontent.com/639730/158915927-1526f6fd-79e3-490c-9073-432fe4a30e45.png)
