### ISSUE TITLE
Hello how to remove the about page in Searxng??

### ISSUE THREAD

**Issue by Mostafaibsharaf019** [searx/searx#3352]
### _**Hello How can I remove the about page in Searxng??**_

**Comment by dalf** [comment]
You can't do with only configuration, you have to hack the template.

You have to remove this line:
https://github.com/searxng/searxng/blob/8a56e3d443d12c1b5f467bdffcb746747a7107ef/searx/templates/simple/base.html#L46

Since you use docker (?), what you can do is (⚠️ this was not tested) :
* you can copy / paste base.html
* remove the line 46
* mount your version of base.html in `/usr/local/searxng/searx/template/simple/base.html` in docker-compose.yml :
```yaml
  searxng:
    container_name: searxng
    image: searxng/searxng:latest   
    volumes:
       ./base.html: /usr/local/searxng/searx/template/simple/base.html
```
