### ISSUE TITLE
All engines time out resulting in no search results (docker DNS issue)

### ISSUE THREAD

**Issue by voronind-com** [searx/searx#3405]
**Version of Searx, commit number if you are using on master branch and stipulate if you forked Searx**
Latest broken version: 1.1.0-32-806bd804 
Latest working version: 1.0.0-349-a1645851

**How did you install Searx?**
official docker images from Docker Hub

**What happened?**
Search not working at all.

**How To Reproduce**
1. Try to search for anything. 
2. See no search suggestions (when enabled).
3. Press enter to search.
4. Wait about 2 sec for default timeout.
5. See all engine timeout errors with no results.

**Expected behavior**
Basic usage working.

**Screenshots & Logs**
![image](https://user-images.githubusercontent.com/22127600/200089627-1830b0b1-3c59-449c-a16a-d6c4c56ef4f7.png)

logs (after reproducing the issue):
```
search  | searx version 1.1.0-32-806bd804
search  | 
search  | Use existing /etc/searx/uwsgi.ini
search  | Use existing /etc/searx/settings.yml
search  | Listen on 0.0.0.0:8080
search  | [uWSGI] getting INI configuration from /etc/searx/uwsgi.ini
search  | [uwsgi-static] added mapping for /static => /usr/local/searx/searx/static

```

docker-compose file:
```
version: '3.8'
services:
  search: 
#    image: docker.io/searx/searx:1.0.0-349-a1645851
    image: docker.io/searx/searx:latest
    container_name: search
    restart: unless-stopped
    user: "0:0"
    cpus: 1.0
    mem_limit: 1G
    logging:
#      driver: "none"
      options:
        max-file: "1"
        max-size: "1m"
    networks:
      docker: 
        ipv4_address: 10.1.0.26
    volumes:
      - ./data:/etc/searx
    environment:
      - BASE_URL=[REMOVED]

networks:
  docker: 
    name: docker
    external: true
```

**Additional context**
I'm using basic configs, aka clean docker install.
Just switching to old working version does the job.
I update quarterly and experiencing this issue for half a year now (3 mo ago I've decided to skip one update).
