### ISSUE TITLE
Using single apostrophe causes a "search error"

### ISSUE THREAD

**Issue by uristdwarf** [searx/searx#3414]
**Version of Searx, commit number if you are using on master branch and stipulate if you forked Searx**
1.1.0-27-bf0a583f

**How did you install Searx?**
searx-docker. Specifically using docker-compose and running ``docker-compose up``.
Compose file:
```yaml
version: '3.3'
services:
    searx:
        volumes:
            - /mnt/storage1/configs/searx:/etc/searx
        ports:
            - 9999:8080
        environment:
            - BASE_URL=http://localhost:9999/
        image: searx/searx
        restart: unless-stopped
```

**What happened?**
Using a single apostrophe in a word (for example, "What's") causes a search error

**How To Reproduce**
Use any single apostrophe in a search query

**Expected behavior**
Should return results, instead of an error.

**Screenshots & Logs**
https://imgur.com/a/E2b4mNX
https://paste.ee/p/e5gS8

**Additional context**
It's also somewhat infuriating that it also returns from a result page to the home page when this happens, meaning I have to retype my query (though that's another issue entirely).
