### ISSUE TITLE
How do I set GET as the default search method?

### ISSUE THREAD

**Issue by der-domi** [searx/searx#703]
Hey all!

How do I set GET as the default search method?

Thanks,
Dominik

**Comment by dalf** [comment]
As far as I know, you must set the preferences for each browser you use.

It can be implemented by replacing : https://github.com/asciimoo/searx/blob/master/searx/preferences.py#L226 with

``` python
 'method': EnumStringSetting(settings['search']['method'] or 'POST', choices=('GET', 'POST')),
```

on settings.yml : 

``` yml
search:
    safe_search : 0 # whatever you want
    autocomplete : "" # whatever you want
    method : "GET"
```
