### ISSUE TITLE
Opensearch doesn't work

### ISSUE THREAD

**Issue by Rinma** [searx/searx#891]
Hello together,

i have a almost working system with Docker, wonderfall/searx image and nginx as reverse proxy. My problem is that Firefox say 
```
Firefox konnte die Suchmaschine nicht herunterladen von:
https://search.example.org/opensearch.xml
---
Firefox can't download this search engine from:
https://search.example.org/opensearch.xml
```

When i open this address `https://search.example.org/opensearch.xml` in my browser i get this xml:
``` 
<OpenSearchDescription>
  <ShortName>searx</ShortName>
  <Description>a privacy-respecting, hackable metasearch engine</Description>
  <InputEncoding>UTF-8</InputEncoding>
  <Image>/static/themes/oscar/img/favicon.png</Image>
  <LongName>searx metasearch</LongName>
  <Url type="text/html" method="post" template="search.over-world.org">
    <Param name="q" value="{searchTerms}"/>
  </Url>
</OpenSearchDescription>
```

My nginx config:
```
server {
    listen 80;
    server_name search.example.org;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    server_name search.example.org;

    ssl_certificate /path/to/cert.pem;
    ssl_certificate_key /path/to/key.pem;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Scheme $scheme;
        proxy_buffering off;

        proxy_pass http://127.0.0.1:7485;
    }
}
```
and the docker-compose file:
```
version: '3'
services:
    searx:
        image: wonderfall/searx
        ports:
            - 127.0.0.1:7485:8888
        environment:
            - IMAGE_PROXY=true
            - BASE_URL=search.example.org
```
The documentation says everything is correct but why i does firefox say it is no valid opensearch xml?
